In [1]:
from housing.config.configuration import Configuartion

ModuleNotFoundError: No module named 'housing'

In [2]:
import os

In [3]:
os.getcwd()

'd:\\iNeuron\\ML_projects\\Housing_Prediction\\notebook'

In [4]:
os.chdir(r'd:\\iNeuron\\ML_projects\\Housing_Prediction')

In [1]:
train_file_path = r'D:\iNeuron\ML_projects\Housing_Prediction\housing\artifact\data_ingestion\2022-09-25-01-54-09\ingested_data\train\housing.csv'

In [44]:
os.path.dirname(train_file_path)

'D:\\iNeuron\\ML_projects\\Housing_Prediction\\housing\\artifact\\data_ingestion\\2022-09-25-01-54-09\\ingested_data\\train'

In [43]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

d:\iNeuron\ML_projects\Consignment Price Prediction\Consignment_price\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
df = pd.read_csv(train_file_path)

In [5]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND  
3       898.0       483.0         2.2264            112500.0      NEAR OCEAN  
4      1837.0       580.0         4.4964            238300.0       <1H OCEAN

In [6]:
df.shape

(16512, 10)

In [23]:
x,y = df.drop(columns=['median_house_value'],axis=1),df['median_house_value']

In [24]:
x.shape

(16512, 9)

In [25]:
x.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [26]:
# to insert data into null value columns
from sklearn.impute import SimpleImputer

In [27]:
simple_imputer = SimpleImputer(strategy='median')

In [28]:
categorical_columns = [column for column in x.columns if x[column].dtype =='O']

In [29]:
x_num = x.drop(categorical_columns,axis=1)

In [30]:
x_num.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  
0      2237.0       706.0         2.1736  
1      2015.0       768.0         6.3373  
2       667.0       300.0         2.8750  
3       898.0       483.0         2.2264  
4      1837.0       580.0         4.4964

In [31]:
simple_imputer.fit_transform(x_num)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [32]:
simple_imputer.transform(x_num)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [33]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [34]:
simple_imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [ ]:
class FeatureGenerator:
    def __init__(self,strategy):
        self.strategy = strategy

    def fit()

    def transform():

    def fit_transform

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [36]:
from sklearn.preprocessing import StandardScaler

In [ ]:
num_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('feature_generator',FeatureGenerator()),
    ('scaling',StandardScaler())
])

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
cat_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('oneHotEncoder',OneHotEncoder()),
    ('scaling',StandardScaler())
])

In [39]:
categorical_columns

['ocean_proximity']

In [40]:
num_columns = x_num.columns

In [ ]:
preprocessing = ColumnTransformer([
    ('num_pipeline', num_pipeline,num_columns),
    ('cat_pipeline', cat_pipeline,categorical_columns)
])

In [41]:
# dump this object in a pkl file

In [42]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(x,y)

In [ ]:
lr.fit_intercept

In [ ]:
lr.coef_

In [ ]:
y_hat = lr.predict(x_test)